### PR TITLE
Added stopwords for Kurdish language

### PR DESCRIPTION
**Pull request by Xoshbin**
Added stopwords for Kurdish language

### CODE REVIEW

**Comment by Xoshbin** [comment]
@Donatello-za About the Kurdish stopwords it's not ku_tr it should be ku_ckb for [Sroani](https://en.wikipedia.org/wiki/Sorani) see [here](https://iso639-3.sil.org/code/ckb) and [here](https://en.wikipedia.org/wiki/Sorani) the one ku_tr is [Kurmanji](https://en.wikipedia.org/wiki/Kurmanji) or [kmr](https://iso639-3.sil.org/code/kmr) which it's not this one that I added mine is Sorani. Sorry for the conflicts I should added it by myself at first.
For the Arabic, Yes I know Arabic and It looks good and there's not much different than the original one. except for one thing, The 'و6' should be changed to 'و', because it doesn't mean anything and for this I had to be more careful because it's in the original one too.

**Comment by Donatello-za** [comment]
Hi @Xoshbin, as you might be aware there are different language code standards, `ku_kcb` is the [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) standard but I am working with the ICU standard where Sorani/Central Kurdish has the code [ckb_IQ](http://www.localeplanet.com/icu/ckb-IQ/index.html). So I changed `ku_TR` to `ckb_IQ` and I hope that will be ok for you.

With regards to the Arabic stop words, I removed the 'و6' stopword (it certainly seems like it is a typo from whoever created the list originally) and then I renamed the `ar.*` stopword files to `ar_AE.php` and `ar_AE.pattern`.

You can look at the [v1.0.12 branch](https://github.com/Donatello-za/rake-php-plus/tree/v1.0.12-dev) and the [commit here](https://github.com/Donatello-za/rake-php-plus/commit/98c5359cd0905aed0e62f4b586ea92b641340a94) and if you are happy with the changes I can release it officially.

**Comment by Xoshbin** [comment]
It looks great for me, I think it's ready to be released. Thank you

**Comment by Donatello-za** [comment]
Thanks for your assistance @Xoshbin, I released v1.0.12, let me know how it works for you.

**Pull request merged**
